//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Windows.Input;
using Locator.Mobile.WP;
using Locator.Mobile.Presentation;
using Locator.Mobile.WP.ViewModels;

namespace Locator.Mobile.WP.ViewModels
{
	public partial class FriendsViewModel : BaseViewModel<FriendsPresenter>, IFriendsView
	{
		private Locator.ServiceContract.Models.FriendsModel friends;
        public Locator.ServiceContract.Models.FriendsModel Friends 
        {
			get { return friends; }
            set 
            { 
                friends = value;
                OnPropertyChanged();
            }
        }

		private Locator.Entity.Entities.User friend;
        public Locator.Entity.Entities.User Friend 
        {
			get { return friend; }
            set 
            { 
                friend = value;
                OnPropertyChanged();
            }
        }

		public event System.Action Refresh;
		public ICommand RefreshCommand { get; private set; }
		partial void RefreshMethod(object o);
		public event System.Action<System.Int64,System.Double,System.Double> SendLocation;
		public ICommand SendLocationCommand { get; private set; }
		partial void SendLocationMethod(object o);
		
		partial void Initialize();

		public FriendsViewModel()
		{
			Initialize();
			RefreshCommand = new Command(RefreshMethod);
			SendLocationCommand = new Command(SendLocationMethod);

		}
	}
}
