//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Windows.Input;
using Locator.Mobile.WP;
using Locator.Mobile.Presentation;
using Locator.Mobile.WP.ViewModels;

namespace Locator.Mobile.WP.ViewModels
{
	public partial class LocationsViewModel : BaseViewModel<LocationsPresenter>, ILocationsView
	{
		private Locator.ServiceContract.Models.LocationsModel locations;
        public Locator.ServiceContract.Models.LocationsModel Locations 
        {
			get { return locations; }
            set 
            { 
                locations = value;
                OnPropertyChanged();
            }
        }

		private Locator.Entity.Entities.Location location;
        public Locator.Entity.Entities.Location Location 
        {
			get { return location; }
            set 
            { 
                location = value;
                OnPropertyChanged();
            }
        }

		public event System.Action Refresh;
		public ICommand RefreshCommand { get; private set; }
		partial void RefreshMethod(object o);
		public event System.Action<System.Int64> OpenLocation;
		public ICommand OpenLocationCommand { get; private set; }
		partial void OpenLocationMethod(object o);
		
		partial void Initialize();

		public LocationsViewModel()
		{
			Initialize();
			RefreshCommand = new Command(RefreshMethod);
			OpenLocationCommand = new Command(OpenLocationMethod);

		}
	}
}
