//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Windows.Input;
using Locator.Mobile.WP;
using Locator.Mobile.Presentation;
using Locator.Mobile.WP.ViewModels;

namespace Locator.Mobile.WP.ViewModels
{
	public partial class LocationViewModel : BaseViewModel<LocationPresenter>, ILocationView
	{
		private System.Int64 locationid;
        public System.Int64 LocationId 
        {
			get { return locationid; }
            set 
            { 
                locationid = value;
                OnPropertyChanged();
            }
        }

		private Locator.Entity.Entities.Location location;
        public Locator.Entity.Entities.Location Location 
        {
			get { return location; }
            set 
            { 
                location = value;
                OnPropertyChanged();
            }
        }

		public event System.Action<System.Int64> Refresh;
		public ICommand RefreshCommand { get; private set; }
		partial void RefreshMethod(object o);
		
		partial void Initialize();

		public LocationViewModel()
		{
			Initialize();
			RefreshCommand = new Command(RefreshMethod);

		}
	}
}
