//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Windows.Input;
using Locator.Mobile.WP;
using Locator.Mobile.Presentation;
using Locator.Mobile.WP.ViewModels;

namespace Locator.Mobile.WP.ViewModels
{
	public partial class RegistrationViewModel : BaseViewModel<RegistrationPresenter>, IRegistrationView
	{
		private System.String login;
        public System.String Login 
        {
			get { return login; }
            set 
            { 
                login = value;
                OnPropertyChanged();
            }
        }

		public event System.Action<System.Int64> Register;
		public ICommand RegisterCommand { get; private set; }
		partial void RegisterMethod(object o);
		
		partial void Initialize();

		public RegistrationViewModel()
		{
			Initialize();
			RegisterCommand = new Command(RegisterMethod);

		}
	}
}
